blank_issues_enabled: true
contact_links:
  - name: Universal-DB issue
    url: https://github.com/Universal-Team/db/issues/new/choose
    about: Issues with the app database should go in the db repository
  - name: Support (on Discord)
    url: https://universal-team.net/discord
    about: "Please use #support on the Discord server to for support-related questions"
